# Generated by Django 5.1.3 on 2024-12-09 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('products', '0002_product_is_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='products.product'),
        ),
    ]
