# Generated by Django 5.1.3 on 2025-01-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
