# Generated by Django 5.1.3 on 2024-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
