# Generated by Django 5.1.3 on 2024-12-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Resuelto'), ('dismissed', 'Descartado')], default='pending', max_length=10),
        ),
    ]
